//
//  Constants.swift
//  LIHKG GIFs
//
//  Created by Ice Lam on 26/10/2022.
//

import SwiftUI

struct Constants {
  static let BUNDLE_VERSION = (Bundle.main.infoDictionary?["CFBundleShortVersionString"]  as? String) ?? ""
  static let BUNDLE_NAME = (Bundle.main.infoDictionary!["CFBundleDisplayName"] as? String) ?? ""
  
  static let POPOVER_WIDTH: CGFloat = 300
  static let POPOVER_HEIGHT: CGFloat = 600
  
  static let CAT_GIFS: [String] = [
    "cat_01_smile",
    "cat_02_lick",
    "cat_03_nap",
    "cat_04_bye",
    "cat_05_stare",
    "cat_06_handup",
    "cat_07_annoyed",
    "cat_08_headache",
    "cat_09_throw",
    "cat_10_angry",
    "cat_11_appear",
    "cat_12_darkness",
    "cat_13_threat",
    "cat_14_swipe",
    "cat_15_rain",
    "cat_16_shaking",
    "cat_17_sneeze",
    "cat_18_mask",
    "cat_19_unwell",
    "cat_20_disappointed",
    "cat_21_angel",
    "cat_22_pussy1",
    "cat_23_pussy2",
    "cat_24_stretching",
    "cat_25_lucky",
    "cat_26_lihkg",
  ]
  
  static let COW_GIFS: [String] = [
    "cow_01_smile",
    "cow_02_hehe",
    "cow_03_sad",
    "cow_04_sosad",
    "cow_05_sweat",
    "cow_06_bye",
    "cow_07_hair",
    "cow_08_slap",
    "cow_09_geltau",
    "cow_10_sadbutsmile",
    "cow_11_door",
    "cow_12_grab",
    "cow_13_no",
    "cow_14_sleep",
    "cow_15_plan",
    "cow_16_scheme",
    "cow_17_arrogant",
    "cow_18_cigar",
    "cow_19_wa",
    "cow_20_unexpected",
    "cow_21_ball",
    "cow_22_lose",
    "cow_23_medal",
    "cow_24_gold",
    "cow_25_power",
    "cow_26_sorry",
    "cow_27_arrr",
    "cow_28_bus",
    "cow_29_bicycle",
    "cow_30_car",
    "cow_31_linguistic",
    "cow_32_lihkg",
    "cow_33_power_special",
    "cow_34_bus_special",
  ]
  
  static let DOG_GIFS: [String] = [
    "dog_01_smile",
    "dog_02_hehe",
    "dog_03_haha",
    "dog_04_bye",
    "dog_05_999",
    "dog_06_on_hold",
    "dog_07_phone",
    "dog_08_FBI",
    "dog_09_discover",
    "dog_10_math",
    "dog_11_photo",
    "dog_12_telescope",
    "dog_13_excited",
    "dog_14_lick",
    "dog_15_tasty",
    "dog_16_wet",
    "dog_17_touch",
    "dog_18_play",
    "dog_19_treat",
    "dog_20_injection",
    "dog_21_clean",
    "dog_22_stop",
    "dog_23_no",
    "dog_24_realized",
    "dog_25_scare",
    "dog_26_angry",
    "dog_27_zzz",
    "dog_28_upset",
    "dog_29_notcry",
    "dog_30_cry",
    "dog_31_cheerup",
    "dog_32_give",
    "dog_33_beg",
    "dog_34_itdog0",
    "dog_35_itdog1",
    "dog_36_itdog2",
    "dog_37_itdog3",
    "dog_38_itdog4",
    "dog_39_itdog5",
    "dog_40_run",
    "dog_41_bark",
    "dog_42_escape",
    "dog_43_beat",
    "dog_44_fight1",
    "dog_45_fight2",
    "dog_46_fight3",
    "dog_47_npc2",
    "dog_48_lihkg",
    "dog_49_fight3_special",
    "dog_50_fight_special",
    "dog_51_fight3_special2",
  ]
  
  static let DRAGON_GIFS: [String] = [
    "dragon_01_smile",
    "dragon_02_happy",
    "dragon_03_unclehappy",
    "dragon_04_unclehappy2",
    "dragon_05_lick",
    "dragon_06_lick2",
    "dragon_07_gj",
    "dragon_08_disappear",
    "dragon_09_guitar",
    "dragon_10_bye",
    "dragon_11_eat",
    "dragon_12_ok",
    "dragon_13_drink",
    "dragon_14_think",
    "dragon_15_wtf",
    "dragon_16_phone",
    "dragon_17_mindblown",
    "dragon_18_wheelchair",
    "dragon_19_angry",
    "dragon_20_headache",
    "dragon_21_spit",
    "dragon_22_midfinger",
    "dragon_23_laser",
    "dragon_24_read",
    "dragon_25_sad",
    "dragon_26_sad2",
    "dragon_27_nope",
    "dragon_28_shock",
    "dragon_29_backpain",
    "dragon_30_shiver",
    "dragon_31_z",
    "dragon_32_wind",
    "dragon_33_lihkg",
    "dragon_34_angry_special",
  ]
  
  static let MOUSE_GIFS: [String] = [
    "mouse_01_smile",
    "mouse_02_pray",
    "mouse_03_please",
    "mouse_04_miracle",
    "mouse_05_yea",
    "mouse_06_ohyes",
    "mouse_07_bye",
    "mouse_08_fuck",
    "mouse_09_short",
    "mouse_10_there",
    "mouse_11_tea",
    "mouse_12_cheer",
    "mouse_13_cheerleading",
    "mouse_14_love",
    "mouse_15_awake",
    "mouse_16_vampire",
    "mouse_17_coffin",
    "mouse_18_cross",
    "mouse_19_crystalball",
    "mouse_20_potion",
    "mouse_21_solution",
    "mouse_22_gun",
    "mouse_23_medicine",
    "mouse_24_how",
    "mouse_25_what",
    "mouse_26_scratching",
    "mouse_27_ohno",
    "mouse_28_notcry",
    "mouse_29_cry",
    "mouse_30_cryalot",
    "mouse_31_tired",
    "mouse_32_blah",
    "mouse_33_sigh",
    "mouse_34_annoyed",
    "mouse_35_rubbish",
    "mouse_36_wind",
    "mouse_37_lihkg",
    "mouse_38_smile_special",
    "mouse_39_vampire_special",
    "mouse_40_miracle_special",
  ]
  
  static let PIG_GIFS: [String] = [
    "pig_01_smile",
    "pig_02_hate",
    "pig_03_smirk",
    "pig_04_hehe",
    "pig_05_mock",
    "pig_06_clap",
    "pig_07_sowhat",
    "pig_08_bye",
    "pig_09_cut",
    "pig_10_cook",
    "pig_11_fry",
    "pig_12_fan",
    "pig_13_peanut",
    "pig_14_wine",
    "pig_15_champagne",
    "pig_16_play",
    "pig_17_whip",
    "pig_18_shocked",
    "pig_19_read",
    "pig_20_heard",
    "pig_21_nope",
    "pig_22_pointing",
    "pig_23_argue",
    "pig_24_drum",
    "pig_25_speakerphone",
    "pig_26_sadNangry",
    "pig_27_angry",
    "pig_28_knife",
    "pig_29_arrested",
    "pig_30_upset",
    "pig_31_wail",
    "pig_32_wail2",
    "pig_33_wail3",
    "pig_34_sick",
    "pig_35_dance",
    "pig_36_dance2",
    "pig_37_dance3",
    "pig_38_dance4",
    "pig_39_rolling",
    "pig_40_dying",
    "pig_41_surviving",
    "pig_42_free",
    "pig_43_lihkg",
    "pig_44_whip_special",
  ]
  
  static let RABBIT_GIFS: [String] = [
    "rabbit_01_smile",
    "rabbit_02_smile2",
    "rabbit_03_happy",
    "rabbit_04_haha",
    "rabbit_05_clap",
    "rabbit_06_agree",
    "rabbit_07_music",
    "rabbit_08_bye",
    "rabbit_09_blink",
    "rabbit_10_hear",
    "rabbit_11_confuse",
    "rabbit_12_wtf",
    "rabbit_13_angry",
    "rabbit_14_axe",
    "rabbit_15_banghead",
    "rabbit_16_orange",
    "rabbit_17_emo",
    "rabbit_18_dance",
    "rabbit_19_sweat",
    "rabbit_20_trauma",
    "rabbit_21_sad",
    "rabbit_22_creepy",
    "rabbit_23_scary",
    "rabbit_24_drink",
    "rabbit_25_eat",
    "rabbit_26_saw",
    "rabbit_27_stun",
    "rabbit_28_tape",
    "rabbit_29_yawn",
    "rabbit_30_fly",
    "rabbit_31_lihkg",
    "rabbit_32_clap_special",
    "rabbit_33_lihkg_special",
    "rabbit_34_roast_special",
    "rabbit_35_eat_connect",
    "rabbit_36_hammer_connect",
    "rabbit_37_roast_connect",
  ]
  
  static let SNAKE_GIFS: [String] = [
    "snake_01_smile",
    "snake_02_laugh",
    "snake_03_nose",
    "snake_04_want",
    "snake_05_knife",
    "snake_06_shotgun",
    "snake_07_explosion",
    "snake_08_sweat",
    "snake_09_write",
    "snake_10_confuse",
    "snake_11_wtf",
    "snake_12_scream",
    "snake_13_shock",
    "snake_14_wow",
    "snake_15_boring",
    "snake_16_sad",
    "snake_17_bye",
    "snake_18_eat",
    "snake_19_drink",
    "snake_20_think",
    "snake_21_hypnosis",
    "snake_22_arcade",
    "snake_23_sign",
    "snake_24_zzz",
    "snake_25_lihkg",
    "snake_26_shotgun_special",
    "snake_27_eat_special",
  ]
  
  static let TIGER_GIFS: [String] = [
    "tiger_01_smile",
    "tiger_02_happy",
    "tiger_03_slap",
    "tiger_04_bye",
    "tiger_05_hello",
    "tiger_06_glasses",
    "tiger_07_money",
    "tiger_08_sad",
    "tiger_09_sweat",
    "tiger_10_donno",
    "tiger_11_no",
    "tiger_12_angry",
    "tiger_13_fire",
    "tiger_14_oh",
    "tiger_15_nlhg",
    "tiger_16_pcr",
    "tiger_17_popcorn",
    "tiger_18_champagne",
    "tiger_19_lieflat",
    "tiger_20_like",
    "tiger_21_like2",
    "tiger_22_punchbag",
    "tiger_23_rpg7",
    "tiger_24_lihkg",
    "tiger_25_lihkg2",
    "tiger_26_fire_special",
    "tiger_27_sad_special",
    "tiger_28_shock_special",
    "tiger_29_like_special",
    "tiger_30_punch_special",
    "tiger_31_404",
  ]
  
  static let GIFS: KeyValuePairs = [
    "cat": CAT_GIFS,
    "cow": COW_GIFS,
    "dog": DOG_GIFS,
    "dragon": DRAGON_GIFS,
    "mouse": MOUSE_GIFS,
    "pig": PIG_GIFS,
    "rabbit": RABBIT_GIFS,
    "snake": SNAKE_GIFS,
    "tiger": TIGER_GIFS,
  ]
}
