//
//  Constants.swift
//  LIHKG GIFs
//
//  Created by Ice Lam on 26/10/2022.
//

struct Constants {
  static let CAT_GIFS = [
    "cat_01_smile",
    "cat_02_lick",
    "cat_03_nap",
    "cat_04_bye",
    "cat_05_stare",
    "cat_06_handup",
    "cat_07_annoyed",
    "cat_08_headache",
    "cat_09_throw",
    "cat_10_angry",
    "cat_11_appear",
    "cat_12_darkness",
    "cat_13_threat",
    "cat_14_swipe",
    "cat_15_rain",
    "cat_16_shaking",
    "cat_17_sneeze",
    "cat_18_mask",
    "cat_19_unwell",
    "cat_20_disappointed",
    "cat_21_angel",
    "cat_22_pussy1",
    "cat_23_pussy2",
    "cat_24_stretching",
    "cat_25_lucky",
    "cat_26_lihkg",
  ]
  
  
  static let COW_GIFS = [
    "cow_01_smile",
    "cow_02_hehe",
    "cow_03_sad",
    "cow_04_sosad",
    "cow_05_sweat",
    "cow_06_bye",
    "cow_07_hair",
    "cow_08_slap",
    "cow_09_sadbutsmile",
    "cow_10_door",
    "cow_11_grab",
    "cow_12_no",
    "cow_13_sleep",
    "cow_14_plan",
    "cow_15_scheme",
    "cow_16_arrogant",
    "cow_17_cigar",
    "cow_18_wa",
    "cow_19_unexpected",
    "cow_20_ball",
    "cow_21_medal",
    "cow_22_gold",
    "cow_23_power",
    "cow_24_sorry",
    "cow_25_arrr",
    "cow_26_bus",
    "cow_27_bicycle",
    "cow_28_car",
    "cow_29_linguistic",
    "cow_30_lihkg",
    "cow_31_power_special",
    "cow_32_bus_special",
  ]
  
  static let DOG_GIFS = [
    "dog_01_smile",
    "dog_02_hehe",
    "dog_03_haha",
    "dog_04_bye",
    "dog_05_999",
    "dog_06_on_hold",
    "dog_07_phone",
    "dog_08_FBI",
    "dog_09_discover",
    "dog_10_math",
    "dog_11_photo",
    "dog_12_telescope",
    "dog_13_excited",
    "dog_14_lick",
    "dog_15_tasty",
    "dog_16_wet",
    "dog_17_touch",
    "dog_18_play",
    "dog_19_treat",
    "dog_20_injection",
    "dog_21_clean",
    "dog_22_stop",
    "dog_23_no",
    "dog_24_realized",
    "dog_25_scare",
    "dog_26_angry",
    "dog_27_zzz",
    "dog_28_upset",
    "dog_29_notcry",
    "dog_30_cry",
    "dog_31_cheerup",
    "dog_32_give",
    "dog_33_beg",
    "dog_34_itdog0",
    "dog_35_itdog1",
    "dog_36_itdog2",
    "dog_37_itdog3",
    "dog_38_itdog4",
    "dog_39_itdog5",
    "dog_40_run",
    "dog_41_bark",
    "dog_42_escape",
    "dog_43_beat",
    "dog_44_fight1",
    "dog_45_fight2",
    "dog_46_npc2",
    "dog_47_lihkg",
  ]
  
  static let MOUSE_GIFS = [
    "mouse_01_smile",
    "mouse_02_pray",
    "mouse_03_please",
    "mouse_04_miracle",
    "mouse_05_yea",
    "mouse_06_ohyes",
    "mouse_07_bye",
    "mouse_08_fuck",
    "mouse_09_short",
    "mouse_10_there",
    "mouse_11_tea",
    "mouse_12_cheer",
    "mouse_13_cheerleading",
    "mouse_14_love",
    "mouse_15_awake",
    "mouse_16_vampire",
    "mouse_17_coffin",
    "mouse_18_cross",
    "mouse_19_crystalball",
    "mouse_20_potion",
    "mouse_21_solution",
    "mouse_22_gun",
    "mouse_23_medicine",
    "mouse_24_how",
    "mouse_25_what",
    "mouse_26_scratching",
    "mouse_27_ohno",
    "mouse_28_notcry",
    "mouse_29_cry",
    "mouse_30_cryalot",
    "mouse_31_tired",
    "mouse_32_blah",
    "mouse_33_sigh",
    "mouse_34_annoyed",
    "mouse_35_rubbish",
    "mouse_36_lihkg",
  ]
  
  static let PIG_GIFS = [
    "pig_01_smile",
    "pig_02_hate",
    "pig_03_smirk",
    "pig_04_hehe",
    "pig_05_mock",
    "pig_06_clap",
    "pig_07_sowhat",
    "pig_08_bye",
    "pig_09_cut",
    "pig_10_cook",
    "pig_11_fry",
    "pig_12_fan",
    "pig_13_peanut",
    "pig_14_wine",
    "pig_15_champagne",
    "pig_16_play",
    "pig_17_whip",
    "pig_18_shocked",
    "pig_19_read",
    "pig_20_heard",
    "pig_21_nope",
    "pig_22_pointing",
    "pig_23_argue",
    "pig_24_drum",
    "pig_25_speakerphone",
    "pig_26_sadNangry",
    "pig_27_angry",
    "pig_28_knife",
    "pig_29_arrested",
    "pig_30_upset",
    "pig_31_wail",
    "pig_32_wail2",
    "pig_33_wail3",
    "pig_34_sick",
    "pig_35_dance",
    "pig_36_dance2",
    "pig_37_dance3",
    "pig_38_dance4",
    "pig_39_dying",
    "pig_40_surviving",
    "pig_41_free",
    "pig_42_lihkg",
  ]
  
  static let TIGER_GIFS = [
    "tiger_01_smile",
    "tiger_02_happy",
    "tiger_03_slap",
    "tiger_04_bye",
    "tiger_05_hello",
    "tiger_06_glasses",
    "tiger_07_money",
    "tiger_08_sad",
    "tiger_09_sweat",
    "tiger_10_donno",
    "tiger_11_no",
    "tiger_12_angry",
    "tiger_13_fire",
    "tiger_14_oh",
    "tiger_15_nlhg",
    "tiger_16_pcr",
    "tiger_17_popcorn",
    "tiger_18_champagne",
    "tiger_19_like",
    "tiger_20_like2",
    "tiger_21_punchbag",
    "tiger_22_rpg7",
    "tiger_23_lihkg",
    "tiger_24_lihkg2",
    "tiger_25_sad_special",
    "tiger_26_shock_special",
    "tiger_27_like_special",
    "tiger_28_punch_special",
  ]
  
  static let GIFS: KeyValuePairs = [
    "Cat": CAT_GIFS,
    "Cow": COW_GIFS,
    "Dog": DOG_GIFS,
    "Mouse": MOUSE_GIFS,
    "Pig": PIG_GIFS,
    "Tiger": TIGER_GIFS
  ]
}
